<%@ Page Title="" Language="C#" MasterPageFile="~/Master/Master.Master" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="MG.Formularios.Chat.Chat" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contenidoPrincipal" runat="server">
    <div id="Div1" class="form-horizontal text-center col-sm-12 col-md-12" runat="server">

        <fieldset>

            <legend>

                <asp:Label class="h1" ID="lblComentariosTitle" runat="server" Text="Sala de Chat" ></asp:Label>

            </legend>
            <div class="col-sm-6">
                <div class="text-center">
                    <img class="img-responsive" src="../../Imagenes/logoMX.jpg" />

                </div>
            </div>
            <div class="col-sm-6">



                <div class="col-sm-12">
                    <asp:Label ID="lblComentario" For="textArea" class=" h2 col-sm-12  text-center" runat="server" Text="Chat" ></asp:Label>
                    <div class="top-xlspace"></div>
                    <input type="text" id="message" size="50" />
                    <div class="top-smspace"></div>
                    <button type="button" id="sendmessage" value="Enviar" class="btn btn-primary">Enviar</button>
                    <div class="top-smspace"></div>
                    <input type="hidden" id="displayname" />
                    <ul id="discussion">
                    </ul>
                </div>

                <!--Script references. -->
                <!--Reference the jQuery library. -->

                <!--Reference the SignalR library. -->
                <script src="/Scripts/jquery.signalR-2.2.1.min.js"></script>
                <!--Reference the autogenerated SignalR hub script. -->
                <script src="/signalr/hubs"></script>
                <!--Add script to update the page and send messages.-->
                <script type="text/javascript">
                    $(function () {
                        // Declare a proxy to reference the hub. 
                        var chat = $.connection.chatHub;
                        // Create a function that the hub can call to broadcast messages.
                        chat.client.broadcastMessage = function (name, message) {
                            // Html encode display name and message. 
                            var encodedName = $('<div />').text(name).html();
                            var encodedMsg = $('<div />').text(message).html();
                            // Add the message to the page. 
                            $('#discussion').append('<li><strong>' + encodedName
                                + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
                        };
                        // Get the user name and store it to prepend to messages.
                        $('#displayname').val(prompt('Enter your name:', ''));
                        // Set initial focus to message input box.  
                        $('#message').focus();
                        // Start the connection.
                        $.connection.hub.start().done(function () {
                            $('#sendmessage').click(function () {
                                // Call the Send method on the hub. 
                                chat.server.send($('#displayname').val(), $('#message').val());
                                // Clear text box and reset focus for next comment. 
                                $('#message').val('').focus();
                            });
                        });
                    });
                </script>
            </div>

        </fieldset>
    </div>
</asp:Content>
